name: Scrape and Update Links

on:
  schedule:
    - cron: '0 4 * * *' # Runs every day at 4 am UTC
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # You can change this to your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python ./scrape_v5.py

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add links.v5.json
          git diff --staged --quiet || git commit -m "Automated scrape: Update links.v5.json" && git push
