name: Update TMDB Data

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  update-tmdb-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run TMDB script
        run: python tmdb.py
        working-directory: ./movies

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automated TMDB data update'
          branch: main
          file_pattern: 'movies/titles/*.json movies/posters/*.png'